const galleryItems = [
  {
    id: 1,
    title: "Award Ceremony",
    date: "2023-12-15",
    images: [
      "/gallery/Award/award_(1).JPG",
      "/gallery/Award/award_(2).JPG",
      "/gallery/Award/award_(3).JPG",
      "/gallery/Award/award_(4).JPG",
      "/gallery/Award/award_(5).JPG",
      "/gallery/Award/award_(6).JPG",
      "/gallery/Award/award_(7).JPG",
      "/gallery/Award/award_(8).JPG",
      "/gallery/Award/award_(9).JPG",
      "/gallery/Award/award_(10).JPG",
      "/gallery/Award/award_(11).JPG",
      "/gallery/Award/award_(12).JPG",
      "/gallery/Award/award_(13).JPG",
      "/gallery/Award/award_(14).JPG",
      "/gallery/Award/award_(15).JPG",
      "/gallery/Award/award_(16).JPG",
      "/gallery/Award/award_(17).JPG",
      "/gallery/Award/award_(18).JPG",
      "/gallery/Award/award_(19).JPG",
      "/gallery/Award/award_(20).JPG",
      "/gallery/Award/award_(21).JPG",
      "/gallery/Award/award_(22).JPG",
      "/gallery/Award/award_(23).JPG",
      "/gallery/Award/award_(24).JPG",
      "/gallery/Award/award_(25).JPG",
      "/gallery/Award/award_(26).JPG",
      "/gallery/Award/award_(27).JPG",
      "/gallery/Award/award_(28).JPG",
      "/gallery/Award/award_(29).JPG",
      "/gallery/Award/award_(30).JPG",
    ],
  },
  {
    id: 2,
    title: "Graduation Day",
    date: "2023-11-20",
    images: [
      "/gallery/Graduation/graduation (1).jpg",
      "/gallery/Graduation/graduation (2).jpg",
      "/gallery/Graduation/graduation (3).jpg",
      "/gallery/Graduation/graduation (4).jpg", 
      "/gallery/Graduation/graduation (5).jpg",
      "/gallery/Graduation/graduation (6).jpg",
      "/gallery/Graduation/graduation (7).jpg",
      "/gallery/Graduation/graduation (8).jpg",
      "/gallery/Graduation/graduation (9).jpg",
      "/gallery/Graduation/graduation (10).jpg",
      "/gallery/Graduation/graduation (11).jpg",
      "/gallery/Graduation/graduation (12).jpg",
      "/gallery/Graduation/graduation (13).jpg",
      "/gallery/Graduation/graduation (14).jpg",
      "/gallery/Graduation/graduation (15).jpg",
      "/gallery/Graduation/graduation (16).jpg",
      "/gallery/Graduation/graduation (17).jpg",
      "/gallery/Graduation/graduation (18).jpg",
      "/gallery/Graduation/graduation (19).jpg",
      "/gallery/Graduation/graduation (20).jpg",
      "/gallery/Graduation/graduation (21).jpg",
      "/gallery/Graduation/graduation (22).jpg",
      "/gallery/Graduation/graduation (23).jpg",
      "/gallery/Graduation/graduation (24).jpg",
      "/gallery/Graduation/graduation (25).jpg",
      "/gallery/Graduation/graduation (26).jpg",
      "/gallery/Graduation/graduation (27).jpg",
      "/gallery/Graduation/graduation (28).jpg",
      "/gallery/Graduation/graduation (29).jpg",
      "/gallery/Graduation/graduation (30).jpg",
      "/gallery/Graduation/graduation (31).jpg",
    ],
  },
  {
    id: 3,
    title: "Hackathon 2023",
    date: "2023-10-05",
    images: [
      "/gallery/Hackathon/hackathon (1).JPG",
      "/gallery/Hackathon/hackathon (2).JPG",
      "/gallery/Hackathon/hackathon (3).JPG",
      "/gallery/Hackathon/hackathon (4).JPG",
      "/gallery/Hackathon/hackathon (5).JPG",
      "/gallery/Hackathon/hackathon (6).JPG",
      "/gallery/Hackathon/hackathon (7).JPG",
      "/gallery/Hackathon/hackathon (8).JPG",
      "/gallery/Hackathon/hackathon (9).JPG",
      "/gallery/Hackathon/hackathon (10).JPG",
      "/gallery/Hackathon/hackathon (11).JPG",
      "/gallery/Hackathon/hackathon (12).JPG",
      "/gallery/Hackathon/hackathon (13).JPG",
      "/gallery/Hackathon/hackathon (14).JPG",
      "/gallery/Hackathon/hackathon (15).JPG",
      "/gallery/Hackathon/hackathon (16).JPG",
      "/gallery/Hackathon/hackathon (17).JPG",
      "/gallery/Hackathon/hackathon (18).JPG",
      "/gallery/Hackathon/hackathon (19).JPG",
      "/gallery/Hackathon/hackathon (20).JPG",
      "/gallery/Hackathon/hackathon (21).JPG",
      "/gallery/Hackathon/hackathon (22).JPG",
      "/gallery/Hackathon/hackathon (23).JPG",
      "/gallery/Hackathon/hackathon (24).JPG",
      "/gallery/Hackathon/hackathon (25).JPG",
      "/gallery/Hackathon/hackathon (26).JPG",
      "/gallery/Hackathon/hackathon (27).JPG",
      "/gallery/Hackathon/hackathon (28).JPG",
      "/gallery/Hackathon/hackathon (29).JPG",
    ],
  },
  {
    id: 4,
    title: "Holi Celebration",
    date: "2023-03-08",
    images: [
      "/gallery/Holi/holi (1).JPG",
      "/gallery/Holi/holi (2).JPG",
      "/gallery/Holi/holi (3).JPG",
      "/gallery/Holi/holi (4).JPG",
      "/gallery/Holi/holi (5).JPG",
      "/gallery/Holi/holi (6).JPG",
      "/gallery/Holi/holi (7).JPG",
      "/gallery/Holi/holi (8).JPG",
      "/gallery/Holi/holi (9).JPG",
      "/gallery/Holi/holi (10).JPG",
      "/gallery/Holi/holi (11).JPG",
      "/gallery/Holi/holi (12).JPG",
      "/gallery/Holi/holi (13).JPG",
      "/gallery/Holi/holi (14).JPG",
      "/gallery/Holi/holi (15).JPG",
      "/gallery/Holi/holi (16).JPG",
      "/gallery/Holi/holi (17).JPG",
      "/gallery/Holi/holi (18).JPG",
      "/gallery/Holi/holi (19).JPG",
      "/gallery/Holi/holi (20).JPG",
      "/gallery/Holi/holi (21).JPG",
      "/gallery/Holi/holi (22).JPG",
      "/gallery/Holi/holi (23).JPG",
      "/gallery/Holi/holi (24).JPG",
      "/gallery/Holi/holi (25).JPG",
      "/gallery/Holi/holi (26).JPG",
      "/gallery/Holi/holi (27).JPG",
      "/gallery/Holi/holi (28).JPG",
      "/gallery/Holi/holi (29).JPG",
    ],
  },
];

export default galleryItems;
